### PR TITLE
Add configurable bucket option (new Arc option)

### PR DESCRIPTION
**Pull request by nihalgonsalves**
The uploader definition now supports a customisable bucket name. The Arc S3 uploader supports this already, and this PR adds support for the same option to Arc GCS.

I'm not sure what environment settings are needed for tests to run - I can try it out if a maintainer gives me some more info, but the current setup works for us already (albeit with a broken test suite).

reference: https://github.com/stavro/arc#specify-multiple-buckets

### CODE REVIEW

**Comment by nihalgonsalves** [comment]
Thanks for the comments @ammbot 

Arc defines a default `bucket/0` here: https://github.com/stavro/arc/blob/master/lib/arc/definition/storage.ex#L7 so Arc GCS doesn't really need to call `Application.fetch_env` directly. The only problem was that I left out support for the `{:system, env_var}` syntax. I've added it back now!

**Comment by nihalgonsalves** [comment]
Hm, looks like the use of `fetch_env!` in Arc's default Storage Definition is problematic because Arc GCS also supports a bucket not being configured at all, unlike (I'm assuming) Arc Local/AWS S3.

I suppose we'd have to do our own `fetch_env` in this case to maintain backwards compatibility (a breaking change but cleaner code could be to require users to set `nil` explicitly for the bucket config). What do you think?

**Comment by samhamilton** [comment]
@nihalgonsalves you will need to set a couple of env_vars to run the tests https://github.com/martide/arc_gcs#tests

**Comment by pierot** [comment]
Would be great if this could be finalised.

**Comment by nihalgonsalves** [comment]
@pierot I'll try to find time for this next week

**Comment by pierot** [comment]
@ammbot @nihalgonsalves why is this PR closed?

**Pull request closed without merging**
